services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: barriotickera
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=PasswordSeguro
    volumes:
      - ticketera_data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  ticketera_data:
