ALTER SESSION SET CONTAINER = FREEPDB1;

-- Creación de usuario y permisos
CREATE USER TICKETERA_APP IDENTIFIED BY "SuperDuperPassword"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

ALTER USER TICKETERA_APP QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, RESOURCE TO TICKETERA_APP;
