-- ============================================================
-- PROYECTO: CUPONERA DIGITAL
-- MOTOR: ORACLE DATABASE
-- ============================================================

-- APLICAR SCRIPT EN EL CONTENEDOR Y ESQUEMA DEL APLICATIVO
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TICKETERA_APP;

-- ============================================================
-- ELIMINACIÓN DE TABLAS
-- ============================================================

-- DROP TABLE CONSUMOS_ENTRADAS CASCADE CONSTRAINTS;
-- DROP TABLE REGISTROS_EVENTOS CASCADE CONSTRAINTS;
-- DROP TABLE ENTRADAS CASCADE CONSTRAINTS;
-- DROP TABLE SERVICIOS_EVENTOS CASCADE CONSTRAINTS;
-- DROP TABLE TIPOS_ENTRADAS CASCADE CONSTRAINTS;
-- DROP TABLE VENTAS_ENTRADAS CASCADE CONSTRAINTS;
-- DROP TABLE COMPRADORES CASCADE CONSTRAINTS;
-- DROP TABLE ESTADOS_ENTRADAS CASCADE CONSTRAINTS;
-- DROP TABLE EVENTOS CASCADE CONSTRAINTS;
-- DROP TABLE ESTADOS_EVENTOS CASCADE CONSTRAINTS;
-- DROP TABLE LOCACIONES CASCADE CONSTRAINTS;
-- DROP TABLE MIEMBROS_ORGANIZACIONES CASCADE CONSTRAINTS;
-- DROP TABLE PERSONAS_ORGANIZACION CASCADE CONSTRAINTS;
-- DROP TABLE ORGANIZACIONES CASCADE CONSTRAINTS;
-- DROP TABLE TIPOS_ORGANIZACIONES CASCADE CONSTRAINTS;
-- DROP TABLE COMUNAS CASCADE CONSTRAINTS;
-- DROP TABLE CIUDADES CASCADE CONSTRAINTS;
-- DROP TABLE REGIONES CASCADE CONSTRAINTS;

-- ============================================================
-- 1. REGIONES
-- ============================================================

CREATE TABLE REGIONES (
    id_region  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_regiones
        PRIMARY KEY (id_region),
    CONSTRAINT uq_regiones_nombre
        UNIQUE (nombre)
);


-- ============================================================
-- 2. CIUDADES
-- ============================================================

CREATE TABLE CIUDADES (
    id_ciudad  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR2(100) NOT NULL,
    id_region  NUMBER NOT NULL,
    CONSTRAINT pk_ciudades
        PRIMARY KEY (id_ciudad),
    CONSTRAINT fk_ciudades_region
        FOREIGN KEY (id_region)
        REFERENCES REGIONES(id_region)
);


-- ============================================================
-- 3. COMUNAS
-- ============================================================

CREATE TABLE COMUNAS (
    id_comuna  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR2(100) NOT NULL,
    id_ciudad  NUMBER NOT NULL,
    CONSTRAINT pk_comunas
        PRIMARY KEY (id_comuna),
    CONSTRAINT fk_comunas_ciudad
        FOREIGN KEY (id_ciudad)
        REFERENCES CIUDADES(id_ciudad)
);


-- ============================================================
-- 4. TIPOS DE ORGANIZACIONES
-- ============================================================

CREATE TABLE TIPOS_ORGANIZACIONES (
    id_tipo_organizacion  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_tipos_organizaciones
        PRIMARY KEY (id_tipo_organizacion),
    CONSTRAINT uq_tipo_organizacion_nombre
        UNIQUE (nombre)
);


-- ============================================================
-- 5. ORGANIZACIONES
-- ============================================================

CREATE TABLE ORGANIZACIONES (
    id_organizacion       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR2(150) NOT NULL,
    rut                   NUMBER(8) NOT NULL,
    dv                    CHAR(1) NOT NULL,
    id_tipo_organizacion  NUMBER NOT NULL,
    CONSTRAINT pk_organizaciones
        PRIMARY KEY (id_organizacion),
    CONSTRAINT uq_organizaciones_rut
        UNIQUE (rut),
    CONSTRAINT fk_org_tipo_organizacion
        FOREIGN KEY (id_tipo_organizacion)
        REFERENCES TIPOS_ORGANIZACIONES(id_tipo_organizacion)
);


-- ============================================================
-- 6. PERSONAS DE LA ORGANIZACIÓN
-- ============================================================

CREATE TABLE PERSONAS_ORGANIZACION (
    id_persona_org    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rut               NUMBER(8) NOT NULL,
    dv                CHAR(1) NOT NULL,
    primer_nombre     VARCHAR2(50) NOT NULL,
    segundo_nombre    VARCHAR2(50),
    primer_apellido   VARCHAR2(50) NOT NULL,
    segundo_apellido  VARCHAR2(50),
    correo            VARCHAR2(150),
    fono              VARCHAR2(20),
    direccion         VARCHAR2(200),
    id_comuna         NUMBER,
    CONSTRAINT pk_personas_organizacion
        PRIMARY KEY (id_persona_org),
    CONSTRAINT uq_personas_org_rut
        UNIQUE (rut),
    CONSTRAINT fk_personas_org_comuna
        FOREIGN KEY (id_comuna)
        REFERENCES COMUNAS(id_comuna)
);


-- ============================================================
-- 7. MIEMBROS DE ORGANIZACIONES
-- ============================================================

CREATE TABLE MIEMBROS_ORGANIZACIONES (
    id_miembro_org  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rol             VARCHAR2(100) NOT NULL,
    id_persona_org  NUMBER NOT NULL,
    id_organizacion NUMBER NOT NULL,
    CONSTRAINT pk_miembros_organizaciones
        PRIMARY KEY (id_miembro_org),
    CONSTRAINT fk_miembro_persona
        FOREIGN KEY (id_persona_org)
        REFERENCES PERSONAS_ORGANIZACION(id_persona_org),
    CONSTRAINT fk_miembro_organizacion
        FOREIGN KEY (id_organizacion)
        REFERENCES ORGANIZACIONES(id_organizacion),
    CONSTRAINT uq_miembro_organizacion
        UNIQUE (id_persona_org, id_organizacion)
);


-- ============================================================
-- 8. LOCACIONES
-- ============================================================

CREATE TABLE LOCACIONES (
    id_locacion      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(150) NOT NULL,
    capacidad_max    NUMBER(8) NOT NULL,
    direccion        VARCHAR2(200) NOT NULL,
    fono_contacto    VARCHAR2(20),
    correo_contacto  VARCHAR2(150),
    id_comuna        NUMBER NOT NULL,
    CONSTRAINT pk_locaciones
        PRIMARY KEY (id_locacion),
    CONSTRAINT fk_locaciones_comuna
        FOREIGN KEY (id_comuna)
        REFERENCES COMUNAS(id_comuna),
    CONSTRAINT ck_locaciones_capacidad
        CHECK (capacidad_max > 0)
);


-- ============================================================
-- 9. ESTADOS DE EVENTOS
-- ============================================================

CREATE TABLE ESTADOS_EVENTOS (
    id_estado_evento  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre            VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_estados_eventos
        PRIMARY KEY (id_estado_evento),
    CONSTRAINT uq_estado_evento_nombre
        UNIQUE (nombre)
);


-- ============================================================
-- 10. EVENTOS
-- ============================================================

CREATE TABLE EVENTOS (
    id_evento          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre             VARCHAR2(150) NOT NULL,
    descripcion        VARCHAR2(1000),
    hora_apertura      TIMESTAMP NOT NULL,
    hora_cierre        TIMESTAMP NOT NULL,
    id_estado_evento   NUMBER NOT NULL,
    id_locacion        NUMBER NOT NULL,
    id_organizacion    NUMBER NOT NULL,
    CONSTRAINT pk_eventos
        PRIMARY KEY (id_evento),
    CONSTRAINT fk_eventos_estado
        FOREIGN KEY (id_estado_evento)
        REFERENCES ESTADOS_EVENTOS(id_estado_evento),
    CONSTRAINT fk_eventos_locacion
        FOREIGN KEY (id_locacion)
        REFERENCES LOCACIONES(id_locacion),
    CONSTRAINT fk_eventos_organizacion
        FOREIGN KEY (id_organizacion)
        REFERENCES ORGANIZACIONES(id_organizacion),
    CONSTRAINT ck_eventos_horario
        CHECK (hora_cierre > hora_apertura)
);


-- ============================================================
-- 11. TIPOS DE ENTRADAS
-- ============================================================

CREATE TABLE TIPOS_ENTRADAS (
    id_tipo_entrada  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(100) NOT NULL,
    valor            NUMBER(12,2) NOT NULL,
    id_evento        NUMBER NOT NULL,
    CONSTRAINT pk_tipos_entradas
        PRIMARY KEY (id_tipo_entrada),
    CONSTRAINT fk_tipo_entrada_evento
        FOREIGN KEY (id_evento)
        REFERENCES EVENTOS(id_evento),
    CONSTRAINT ck_tipo_entrada_valor
        CHECK (valor >= 0),
    CONSTRAINT uq_tipo_entrada_evento
        UNIQUE (id_evento, nombre)
);


-- ============================================================
-- 12. ESTADOS DE ENTRADAS
-- ============================================================

CREATE TABLE ESTADOS_ENTRADAS (
    id_estado_entrada  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre             VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_estados_entradas
        PRIMARY KEY (id_estado_entrada),
    CONSTRAINT uq_estado_entrada_nombre
        UNIQUE (nombre)
);


-- ============================================================
-- 13. COMPRADORES
-- ============================================================

CREATE TABLE COMPRADORES (
    id_comprador  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    correo        VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_compradores
        PRIMARY KEY (id_comprador),
    CONSTRAINT uq_compradores_correo
        UNIQUE (correo)
);


-- ============================================================
-- 14. VENTAS DE ENTRADAS
-- ============================================================

CREATE TABLE VENTAS_ENTRADAS (
    id_venta_entrada  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    timestamp_venta   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    id_comprador      NUMBER NOT NULL,
    CONSTRAINT pk_ventas_entradas
        PRIMARY KEY (id_venta_entrada),
    CONSTRAINT fk_venta_comprador
        FOREIGN KEY (id_comprador)
        REFERENCES COMPRADORES(id_comprador)
);


-- ============================================================
-- 15. ENTRADAS
-- ============================================================

CREATE TABLE ENTRADAS (
    id_entrada         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ubicacion          VARCHAR2(100),
    qr                 VARCHAR2(500) NOT NULL,
    id_tipo_entrada    NUMBER NOT NULL,
    id_evento          NUMBER NOT NULL,
    id_venta_entrada   NUMBER,
    id_estado_entrada  NUMBER NOT NULL,
    CONSTRAINT pk_entradas
        PRIMARY KEY (id_entrada),
    CONSTRAINT uq_entradas_qr
        UNIQUE (qr),
    CONSTRAINT fk_entrada_tipo
        FOREIGN KEY (id_tipo_entrada)
        REFERENCES TIPOS_ENTRADAS(id_tipo_entrada),
    CONSTRAINT fk_entrada_evento
        FOREIGN KEY (id_evento)
        REFERENCES EVENTOS(id_evento),
    CONSTRAINT fk_entrada_venta
        FOREIGN KEY (id_venta_entrada)
        REFERENCES VENTAS_ENTRADAS(id_venta_entrada),
    CONSTRAINT fk_entrada_estado
        FOREIGN KEY (id_estado_entrada)
        REFERENCES ESTADOS_ENTRADAS(id_estado_entrada)
);


-- ============================================================
-- 16. SERVICIOS DE EVENTOS
-- ============================================================

CREATE TABLE SERVICIOS_EVENTOS (
    id_servicio_evento  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(100) NOT NULL,
    descripcion         VARCHAR2(500),
    valor               NUMBER(12,2) NOT NULL,
    id_evento           NUMBER NOT NULL,
    CONSTRAINT pk_servicios_eventos
        PRIMARY KEY (id_servicio_evento),
    CONSTRAINT fk_servicio_evento
        FOREIGN KEY (id_evento)
        REFERENCES EVENTOS(id_evento),
    CONSTRAINT ck_servicio_valor
        CHECK (valor >= 0),
    CONSTRAINT uq_servicio_evento
        UNIQUE (id_evento, nombre)
);


-- ============================================================
-- 17. CONSUMOS DE ENTRADAS
-- ============================================================

CREATE TABLE CONSUMOS_ENTRADAS (
    id_consumo_entrada  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    canjeado            CHAR(1) DEFAULT 'N' NOT NULL,
    id_entrada          NUMBER NOT NULL,
    id_servicio_evento  NUMBER NOT NULL,
    CONSTRAINT pk_consumos_entradas
        PRIMARY KEY (id_consumo_entrada),
    CONSTRAINT fk_consumo_entrada
        FOREIGN KEY (id_entrada)
        REFERENCES ENTRADAS(id_entrada),
    CONSTRAINT fk_consumo_servicio
        FOREIGN KEY (id_servicio_evento)
        REFERENCES SERVICIOS_EVENTOS(id_servicio_evento),
    CONSTRAINT ck_consumo_canjeado
        CHECK (canjeado IN ('S', 'N')),
    CONSTRAINT uq_consumo_entrada_servicio
        UNIQUE (id_entrada, id_servicio_evento)
);


-- ============================================================
-- 18. REGISTROS DE EVENTOS
-- ============================================================

CREATE TABLE REGISTROS_EVENTOS (
    id_registro_evento  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha_finalizacion  TIMESTAMP,
    total_asistentes    NUMBER DEFAULT 0 NOT NULL,
    entradas_emitidas   NUMBER DEFAULT 0 NOT NULL,
    entradas_utilizadas NUMBER DEFAULT 0 NOT NULL,
    entradas_anuladas   NUMBER DEFAULT 0 NOT NULL,
    recaudacion_total   NUMBER(15,2) DEFAULT 0 NOT NULL,
    id_evento           NUMBER NOT NULL,
    CONSTRAINT pk_registros_eventos
        PRIMARY KEY (id_registro_evento),
    CONSTRAINT fk_registro_evento
        FOREIGN KEY (id_evento)
        REFERENCES EVENTOS(id_evento),
    CONSTRAINT uq_registro_evento
        UNIQUE (id_evento),
    CONSTRAINT ck_registro_asistentes
        CHECK (total_asistentes >= 0),
    CONSTRAINT ck_registro_emitidas
        CHECK (entradas_emitidas >= 0),
    CONSTRAINT ck_registro_utilizadas
        CHECK (entradas_utilizadas >= 0),
    CONSTRAINT ck_registro_anuladas
        CHECK (entradas_anuladas >= 0),
    CONSTRAINT ck_registro_recaudacion
        CHECK (recaudacion_total >= 0)
);


-- ============================================================
-- DATOS BASE
-- ============================================================


-- ============================================================
-- ESTADOS DE EVENTOS
-- ============================================================

INSERT INTO ESTADOS_EVENTOS (nombre)
VALUES ('EN PLANIFICACION');

INSERT INTO ESTADOS_EVENTOS (nombre)
VALUES ('PUBLICADO');

INSERT INTO ESTADOS_EVENTOS (nombre)
VALUES ('ACTIVO');

INSERT INTO ESTADOS_EVENTOS (nombre)
VALUES ('FINALIZADO');

INSERT INTO ESTADOS_EVENTOS (nombre)
VALUES ('CANCELADO');


-- ============================================================
-- ESTADOS DE ENTRADAS
-- ============================================================

INSERT INTO ESTADOS_ENTRADAS (nombre)
VALUES ('DISPONIBLE');

INSERT INTO ESTADOS_ENTRADAS (nombre)
VALUES ('VENDIDA');

INSERT INTO ESTADOS_ENTRADAS (nombre)
VALUES ('UTILIZADA');

INSERT INTO ESTADOS_ENTRADAS (nombre)
VALUES ('ANULADA');


COMMIT;
